services:
  sonarqube:
    image: sonarqube:8.9.7-community
    restart: unless-stopped
    ports:
      - 9000:9000
      - 9092:9092
    volumes:
      - 'SonarQube_data:/opt/SonarQube/data'
      - 'SonarQube_extensions:/opt/SonarQube/extensions'
      - 'SonarQube_logs:/opt/SonarQube/logs'

  prometheus:
    image: prom/prometheus
    restart: unless-stopped
    ports:
      - 9090:9090
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml 
    depends_on:
      - app-achat  # Ensure Prometheus waits for the app to start

  grafana:
    image: grafana/grafana
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  db:
  SonarQube_data:
  SonarQube_extensions:
  SonarQube_logs:
  prometheus_data:
  grafana_data:
