global:
  scrape_interval: 15s  # Default scrape interval

scrape_configs:
  - job_name: 'spring-app'
    static_configs:
      - targets: ['app-achat:8089']  # The target should match the name of your Spring app service

